WSU Scholar/WSU Scholar/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WSU_Scholar.Models;

namespace WSU_Scholar.Controllers
{
    public class AuthorsController : Controller
    {
        private ProjectDbContext db = new ProjectDbContext();

        // GET: Authors
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.FnameSortParm = sortOrder == "Firstname" ? "fname_desc" : "Firstname";
            ViewBag.LnameSortParm = String.IsNullOrEmpty(sortOrder) ? "lname_desc" : "";
            ViewBag.UniSortParm = sortOrder == "University" ? "university_desc" : "University";
            ViewBag.CampusSortParm = sortOrder == "Campus" ? "campus_desc" : "Campus";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var Author = from a in db.Author
                           select a;

            if(!String.IsNullOrEmpty(searchString))
            {
                Author = Author.Where(a => a.lname.Contains(searchString)
                                       || a.lname.Contains(searchString));

            }

            switch (sortOrder)
            {
                case "fname_desc":
                    Author = Author.OrderByDescending(a => a.campus);
                    break;
                case "Firstname":
                    Author = Author.OrderBy(a => a.campus);
                    break;
                case "campus_desc":
                    Author = Author.OrderByDescending(a => a.campus);
                    break;
                case "Campus":
                    Author = Author.OrderBy(a => a.campus);
                    break;
                case "lname_desc":
                    Author = Author.OrderByDescending(a => a.lname);
                    break;
                case "university_desc":
                    Author = Author.OrderBy(a => a.university);
                    break;
                case "University" :
                    Author = Author.OrderByDescending(a => a.university);
                    break;
                default:
                    Author = Author.OrderBy(a => a.lname);
                    break;

            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(Author.ToPagedList(pageNumber, pageSize));
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Author.Find(id);

            //var researches = from a in db.ResearchAuthor
            //                 join b in db.Research on a.researchID equals b.ID 
            //                 where a.authorID == author.ID
            //                     select a;
            var researches = from a in db.ResearchAuthor
                             where a.authorID == id
                             select a;

            if (author == null)
            {
                return HttpNotFound();
            }

            List<Research> listResearch = new List<Research>();
            foreach (var item in researches)
            {
                listResearch.Add((Research)item.Research);
            }
            decimal totalGrant = 0;
            //total grants
            try {
                totalGrant = (from a in db.ResearchAuthor where a.authorID == id select a.Research.grants).Sum();
            }
            catch {
            }
                        ViewBag.totalGrant = totalGrant;

            AuthorDetailViewModel result = new AuthorDetailViewModel();
            result.author = author;
            result.research = listResearch;
            return View(result);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName");
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title,fname,lname,schoolID,telephone,email,mobile,university,campus")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Author.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName", author.schoolID);
            return View(author);
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Author.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName", author.schoolID);
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title,fname,lname,schoolID,telephone,email,mobile,university,campus")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName", author.schoolID);
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Author.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Author.Find(id);
            db.Author.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WSU Scholar/WSU Scholar/Controllers/ResearchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WSU_Scholar.Models;
using System.IO;

namespace WSU_Scholar.Controllers
{
    public class ResearchesController : Controller
    {
        private ProjectDbContext db = new ProjectDbContext();

        // GET: Researches
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.SubjectSortParm = sortOrder == "Subject" ? "subject_desc" : "Subject";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.GrantSortParm = sortOrder == "Grant" ? "grant_desc" : "Grant";
            ViewBag.ViewsSortParm = sortOrder == "Views" ? "views_desc" : "Views";
            ViewBag.DownloadsSortParm = sortOrder == "Downloads" ? "downloads_desc" : "Downloads";



            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var Research = from r in db.Research
                           select r;


            if (!String.IsNullOrEmpty(searchString))
            {
                Research = Research.Where(r => r.title.Contains(searchString)
                                       || r.title.Contains(searchString));

            }

            switch (sortOrder)
            {
                case "views_desc":
                    Research = Research.OrderByDescending(r => r.views);
                    break;
                case "Views":
                    Research = Research.OrderBy(r => r.views);
                    break;
                case "downloads_desc":
                    Research = Research.OrderByDescending(r => r.downloads);
                    break;
                case "Downloads":
                    Research = Research.OrderBy(r => r.downloads);
                    break;
                case "subject_desc":
                    Research = Research.OrderByDescending(r => r.subject);
                    break;
                case "Subject":
                    Research = Research.OrderBy(r => r.subject);
                    break;
                case "grant_desc":
                    Research = Research.OrderByDescending(r => r.grants);
                    break;
                case "Grant":
                    Research = Research.OrderBy(r => r.grants);
                    break;
                case "title_desc":
                    Research = Research.OrderByDescending(r => r.title);
                    break;
                case "date_desc":
                    Research = Research.OrderByDescending(r => r.publishedDate);
                    break;
                case "Date":
                    Research = Research.OrderBy(r => r.publishedDate);
                    break;
                default:
                    Research = Research.OrderBy(r => r.title);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(Research.ToPagedList(pageNumber, pageSize));
        }

        // GET: Researches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Research research = db.Research.Find(id);
            Author author = (from a in db.ResearchAuthor where a.researchID == research.ID select a.Author).FirstOrDefault();
            if (research == null)
            {
                return HttpNotFound();
            }
            ResearchDetailsViewModel model = new ResearchDetailsViewModel { research = research, author = author };
            research.views++;
            db.SaveChanges();

            return View(model);
        }

        // GET: Researches/Create
        public ActionResult Create()
        {
            ViewBag.ID = new SelectList(db.Record, "researchID", "fileID");
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName");
            var authors = db.Author.Select(i => new { i.ID, name = i.fname + " " + i.lname }).ToList();
            List<AuthorList> a = new List<AuthorList>();
            foreach (var item in authors)
            {
                a.Add(new AuthorList { ID = item.ID, fullName = item.name });

            }
            ViewBag.authors = a;


            return View();
        }

        // POST: Researches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title,schoolID,publishedDate,subject,grants,views,downloads,abstracts")] Research research, HttpPostedFileBase file)
        {

            if (ModelState.IsValid)
            {
                db.Research.Add(research);
                db.SaveChanges();
                //the following code save file to project folder
                //http://www.mikesdotnetting.com/article/259/asp-net-mvc-5-with-ef-6-working-with-files
                if (file != null && file.ContentLength > 0)
                {
                    var filename = file.FileName.GetHashCode();
                    var saveDir = Server.MapPath("~/files/");
                    var path = Path.Combine(saveDir, filename.ToString());
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(saveDir);
                    }
                    file.SaveAs(path);
                    //the following code maps the file to project
                    Record r = new Record { researchID = research.ID, fileID = filename.ToString() };
                    db.Record.Add(r);
                    db.SaveChanges();

                }

                //this section register the reearch to a author
                //maybe later add in multiple author support
                var formAuthorID = Convert.ToInt32(Request["authors"]);
                var author = db.Author.First(a => a.ID == formAuthorID);

                ResearchAuthor researchAuthor = new ResearchAuthor();
                //researchAuthor.ID = db.ResearchAuthor.Count() + 1;
                researchAuthor.researchID = research.ID;
                researchAuthor.authorID = author.ID;

                db.ResearchAuthor.Add(researchAuthor);
                db.SaveChanges();



                return RedirectToAction("Index");
            }

            ViewBag.ID = new SelectList(db.Record, "researchID", "fileID", research.ID);
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName", research.schoolID);
            return View(research);
        }

        // GET: Researches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Research research = db.Research.Find(id);
            if (research == null)
            {
                return HttpNotFound();
            }

            var authors = db.Author.Select(i => new { i.ID, name = i.fname + " " + i.lname }).ToList();
            List<AuthorList> a = new List<AuthorList>();
            foreach (var item in authors)
            {
                a.Add(new AuthorList { ID = item.ID, fullName = item.name });
            }

            ViewBag.authors = a;
            ViewBag.ID = new SelectList(db.Record, "researchID", "fileID", research.ID);
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName", research.schoolID);
            return View(research);
        }

        // POST: Researches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title,schoolID,publishedDate,subject,grants,views,downloads,abstracts")] Research research)
        {
            if (ModelState.IsValid)
            {
                db.Entry(research).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID = new SelectList(db.Record, "researchID", "fileID", research.ID);
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName", research.schoolID);

            //this section register the reearch to a author
            //maybe later add in multiple author support
            var formAuthorID = Convert.ToInt32(Request["authors"]);
            var author = db.Author.First(a => a.ID == formAuthorID);

            ResearchAuthor researchAuthor = new ResearchAuthor();
            //researchAuthor.ID = db.ResearchAuthor.Count() + 1;
            researchAuthor.researchID = research.ID;
            researchAuthor.authorID = author.ID;

            db.ResearchAuthor.Add(researchAuthor);
            db.SaveChanges();

            return View(research);
        }

        // GET: Researches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Research research = db.Research.Find(id);
            if (research == null)
            {
                return HttpNotFound();
            }
            return View(research);
        }

WSU Scholar/WSU Scholar/Views/Researches/Create.cshtml
@model WSU_Scholar.Models.Research

@{
    ViewBag.Title = "Create";
}

@section headScripts{
    @*
        this code is sourced from here
        https://forums.asp.net/t/2026059.aspx?How+to+add+Rich+Text+Controls+to+textbox+in+asp+net+MVC
    *@
    @*<script src="~/Scripts/tinymce/tinymce.min.js"></script>
    <script type="text/javascript">
        // Initialize your tinyMCE Editor with your preferred options
        tinyMCE.init({
            // General options
            mode: "textareas",
            theme: "modern",
            // Theme options
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
            theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
            theme_advanced_toolbar_location: "top",
            theme_advanced_toolbar_align: "left",
            theme_advanced_statusbar_location: "bottom",
            theme_advanced_resizing: true,

            // Example content CSS (should be your site CSS)
            content_css: "~/Content/Site.css",
        });
    </script>*@
    @*
        This site i mound that have modules to enable a bueatiful multiple select box with search function.
        i could hook this up with ajax to allow users to assign multiple authors in a published research article
        https://select2.github.io/
    *@
<link href="~/Content/select2/select2.css" rel="stylesheet" />
<script src="~/Scripts/select2/select2.js"></script>

}
@Scripts.Render("~bundles/select2" )
    @Scripts.Render("~/bundles/jqueryval")
<h2>Create</h2>


@using (Html.BeginForm("Create", "Researches", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
   

    <div class="form-horizontal">
        <h4>Research</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.schoolID, "schoolID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("schoolID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.schoolID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.publishedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.publishedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.publishedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Authors</label>
            <div class="col-md-10">
               @Html.DropDownList("authors", new MultiSelectList(ViewBag.authors, "ID", "fullName"), new {@*multiple= "multiple"*@ })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grants, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.grants, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.grants, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.views, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.views, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.views, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.downloads, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.downloads, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.downloads, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            `<label class="control-label col-md-2" for="file">Upload</label>
            <div class="col-md-10">
                <input type="file" name="file" id="file" />
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.abstracts, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextAreaFor(model => model.abstracts, new { htmlAttributes = new { @class = "form-control"   } })*@
                @Html.TextAreaFor(model => model.abstracts, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.abstracts, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>


}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WSU Scholar/WSU Scholar/Views/Researches/Details.cshtml
@model WSU_Scholar.Models.ResearchDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Research</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Record.fileID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Record.fileID)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.research.School.schoolName)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.School.schoolName)*@
            @Html.ActionLink(Model.research.School.schoolName, "Details", "Schools", new { id = Model.research.schoolID }, null)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.research.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.research.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.research.publishedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.research.publishedDate)
        </dd>

        <dt>
            Author
        </dt>

        <dd>
            @{
                if (Model.author != null)
                {
                    @Html.ActionLink(@Model.author.FullName, "Details", "Authors", new { id = Model.author.ID }, null)
                }
                else { 
                    @Html.Display("N/A")
                }
}
            
           
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.research.subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.research.subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.research.grants)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.research.grants)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.research.views)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.research.views)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.research.downloads)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.research.downloads)
            
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.research.abstracts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.research.abstracts)
        </dd>
        <dd>
            @Html.ActionLink("Download", "Download", new {id = Model.research.ID })
            
        </dd>

    </dl>
</div>
<p>
    @if (Request.IsAuthenticated)
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.research.ID })<text> |</text>
    }

    @Html.ActionLink("Back to List", "Index")
</p>

WSU Scholar/WSU Scholar/Views/Researches/Index.cshtml
@model PagedList.IPagedList<WSU_Scholar.Models.Research>
@using PagedList.Mvc;
@using Microsoft.AspNet.Identity;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}

<h2>Research</h2>

<div>
    @if (Request.IsAuthenticated)
    {
         @Html.ActionLink("Create New", "Create")
    }
    
    @using (Html.BeginForm("Index", "Researches", FormMethod.Get))
    {
        <p>
            Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }
 
</div>
<table class="table">
    <tr>
        @*<th>
                File ID
            </th>*@
        <th>
            School
        </th>
        <th>
            @Html.ActionLink("Title", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Published Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Subject", "Index", new { sortOrder = ViewBag.SubjectSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Grant", "Index", new { sortOrder = ViewBag.GrantSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Views", "Index", new { sortOrder = ViewBag.ViewsSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Downloads", "Index", new { sortOrder = ViewBag.DownloadsSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Abstract
        </th>
        <th>
        </th>
        <th>
            @if (Request.IsAuthenticated)
            {
                @Html.Label("Admin");
            }
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Record.fileID)
                </td>*@
            <td>
                @Html.ActionLink(item.School.schoolName, "Details", "Schools", new { id = item.schoolID }, null)
            </td>
            <td>
                @Html.ActionLink(item.title, "Details", null, new { id = item.ID }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.publishedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.subject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.grants)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.views)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.downloads)
            </td>
            <td>
                @{
        var trimedAbstract = item.abstracts;
        var abstractMaxLength = 150;
        if (trimedAbstract != null && item.abstracts.Length > abstractMaxLength)
        {
            trimedAbstract = trimedAbstract.Substring(0, abstractMaxLength) + "...";
            //Html.DisplayFor(modelItem => trimedAbstract);
            <text>@trimedAbstract</text>
        }
        else { Html.DisplayFor(modelItem => item.abstracts); }

                }

            </td>
            <td>
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                }
            </td>
            @*<td>
                        @Html.ActionLink("Details", "Details", new { id = item.ID })
                </t*@
            <td>
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                }
            </td>
        </tr>
    }

</table>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))