WSU Scholar/WSU Scholar/Controllers/ResearchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WSU_Scholar.Models;
using System.IO;

namespace WSU_Scholar.Controllers
{
    public class ResearchesController : Controller
    {
        private ProjectDbContext db = new ProjectDbContext();

        // GET: Researches
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.SubjectSortParm = sortOrder == "Subject" ? "subject_desc" : "Subject";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.GrantSortParm = sortOrder == "Grant" ? "grant_desc" : "Grant";
            ViewBag.ViewsSortParm = sortOrder == "Views" ? "views_desc" : "Views";
            ViewBag.DownloadsSortParm = sortOrder == "Downloads" ? "downloads_desc" : "Downloads";



            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var Research = from r in db.Research
                           select r;


            if (!String.IsNullOrEmpty(searchString))
            {
                Research = Research.Where(r => r.title.Contains(searchString)
                                       || r.title.Contains(searchString));

            }

            switch (sortOrder)
            {
                case "views_desc":
                    Research = Research.OrderByDescending(r => r.views);
                    break;
                case "Views":
                    Research = Research.OrderBy(r => r.views);
                    break;
                case "downloads_desc":
                    Research = Research.OrderByDescending(r => r.downloads);
                    break;
                case "Downloads":
                    Research = Research.OrderBy(r => r.downloads);
                    break;
                case "subject_desc":
                    Research = Research.OrderByDescending(r => r.subject);
                    break;
                case "Subject":
                    Research = Research.OrderBy(r => r.subject);
                    break;
                case "grant_desc":
                    Research = Research.OrderByDescending(r => r.grants);
                    break;
                case "Grant":
                    Research = Research.OrderBy(r => r.grants);
                    break;
                case "title_desc":
                    Research = Research.OrderByDescending(r => r.title);
                    break;
                case "date_desc":
                    Research = Research.OrderByDescending(r => r.publishedDate);
                    break;
                case "Date":
                    Research = Research.OrderBy(r => r.publishedDate);
                    break;
                default:
                    Research = Research.OrderBy(r => r.title);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(Research.ToPagedList(pageNumber, pageSize));
        }

        // GET: Researches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Research research = db.Research.Find(id);
            Author author = (from a in db.ResearchAuthor where a.researchID == research.ID select a.Author).FirstOrDefault();
            if (research == null)
            {
                return HttpNotFound();
            }
            ResearchDetailsViewModel model = new ResearchDetailsViewModel { research = research, author = author };
            research.views++;
            db.SaveChanges();

            return View(model);
        }

        // GET: Researches/Create
        public ActionResult Create()
        {
            ViewBag.ID = new SelectList(db.Record, "researchID", "fileID");
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName");
            var authors = db.Author.Select(i => new { i.ID, name = i.fname + " " + i.lname }).ToList();
            List<AuthorList> a = new List<AuthorList>();
            foreach (var item in authors)
            {
                a.Add(new AuthorList { ID = item.ID, fullName = item.name });

            }
            ViewBag.authors = a;


            return View();
        }

        // POST: Researches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,title,schoolID,publishedDate,subject,grants,views,downloads,abstracts")] Research research, HttpPostedFileBase file)
        {

            if (ModelState.IsValid)
            {
                db.Research.Add(research);
                db.SaveChanges();
                //the following code save file to project folder
                //http://www.mikesdotnetting.com/article/259/asp-net-mvc-5-with-ef-6-working-with-files
                if (file != null && file.ContentLength > 0)
                {
                    var filename = file.FileName.GetHashCode();
                    var saveDir = Server.MapPath("~/files/");
                    var path = Path.Combine(saveDir, filename.ToString());
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(saveDir);
                    }
                    file.SaveAs(path);
                    //the following code maps the file to project
                    Record r = new Record { researchID = research.ID, fileID = filename.ToString() };
                    db.Record.Add(r);
                    db.SaveChanges();

                }

                //this section register the reearch to a author
                //maybe later add in multiple author support
                var formAuthorID = Convert.ToInt32(Request["authors"]);
                var author = db.Author.First(a => a.ID == formAuthorID);

                ResearchAuthor researchAuthor = new ResearchAuthor();
                //researchAuthor.ID = db.ResearchAuthor.Count() + 1;
                researchAuthor.researchID = research.ID;
                researchAuthor.authorID = author.ID;

                db.ResearchAuthor.Add(researchAuthor);
                db.SaveChanges();



                return RedirectToAction("Index");
            }

            ViewBag.ID = new SelectList(db.Record, "researchID", "fileID", research.ID);
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName", research.schoolID);
            return View(research);
        }

        // GET: Researches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Research research = db.Research.Find(id);
            if (research == null)
            {
                return HttpNotFound();
            }

            var authors = db.Author.Select(i => new { i.ID, name = i.fname + " " + i.lname }).ToList();
            List<AuthorList> a = new List<AuthorList>();
            foreach (var item in authors)
            {
                a.Add(new AuthorList { ID = item.ID, fullName = item.name });
            }

            ViewBag.authors = a;
            ViewBag.ID = new SelectList(db.Record, "researchID", "fileID", research.ID);
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName", research.schoolID);
            return View(research);
        }

        // POST: Researches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,title,schoolID,publishedDate,subject,grants,views,downloads,abstracts")] Research research)
        {
            if (ModelState.IsValid)
            {
                db.Entry(research).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID = new SelectList(db.Record, "researchID", "fileID", research.ID);
            ViewBag.schoolID = new SelectList(db.School, "ID", "schoolName", research.schoolID);

            //this section register the reearch to a author
            //maybe later add in multiple author support
            var formAuthorID = Convert.ToInt32(Request["authors"]);
            var author = db.Author.First(a => a.ID == formAuthorID);

            ResearchAuthor researchAuthor = new ResearchAuthor();
            //researchAuthor.ID = db.ResearchAuthor.Count() + 1;
            researchAuthor.researchID = research.ID;
            researchAuthor.authorID = author.ID;

            db.ResearchAuthor.Add(researchAuthor);
            db.SaveChanges();

            return View(research);
        }

        // GET: Researches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Research research = db.Research.Find(id);
            if (research == null)
            {
                return HttpNotFound();
            }
            return View(research);
        }

WSU Scholar/WSU Scholar/Controllers/SchoolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WSU_Scholar.Models;

namespace WSU_Scholar.Controllers
{
    public class SchoolsController : Controller
    {
        private ProjectDbContext db = new ProjectDbContext();

        // GET: Schools
        public ActionResult Index()
        {
            return View(db.School.ToList());
        }

        // GET: Schools/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = db.School.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }

            var data = from a in db.Research
                       where a.schoolID == school.ID select a;


            SchoolDetailViewModel result = new SchoolDetailViewModel();
            List<SchoolDetailContainer> container = new List<SchoolDetailContainer>();
            result.school = school;

            foreach (var item in data)
            {
                try
                {
                    var author = db.ResearchAuthor.First(i => i.researchID == item.ID);
                    container.Add(new SchoolDetailContainer {ID= item.ID, title = item.title, publishedDate = item.publishedDate, authorName = author.Author.FullName });
                }
                catch (Exception)
                {
                    container.Add(new SchoolDetailContainer {ID= item.ID, title = item.title, publishedDate = item.publishedDate, authorName = "" });
                }    
                
                   
            }

            result.details = container;


            return View(result);
        }

        // GET: Schools/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Schools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,schoolName,disciplineName")] School school)
        {
            if (ModelState.IsValid)
            {
                db.School.Add(school);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(school);
        }

        // GET: Schools/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = db.School.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        // POST: Schools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,schoolName,disciplineName")] School school)
        {
            if (ModelState.IsValid)
            {
                db.Entry(school).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(school);
        }

        // GET: Schools/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            School school = db.School.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        // POST: Schools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            School school = db.School.Find(id);
            db.School.Remove(school);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WSU Scholar/WSU Scholar/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>

<p>This is a collection of the research performed by WSU academics and their collaborations.</p>

WSU Scholar/WSU Scholar/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    WSU<br />
    Parramatta NSW 2150<br />
    <abbr title="Phone">Phone: 9852 5222</abbr>
</address>

<address>

</address>

WSU Scholar/WSU Scholar/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

}
@model WSU_Scholar.Models.HomeFeedContainerViewModel


@section headScripts{
    <script src="~/Scripts/bubble_tree/bubbletree.js"></script>
    <script src="~/Scripts/bubble_tree/jquery.history.js"></script>
    <script src="~/Scripts/bubble_tree/jquery.min.js"></script>
    <script src="~/Scripts/bubble_tree/jquery.tooltip.min.js"></script>
    <script src="~/Scripts/bubble_tree/raphael-min.js"></script>
    <script src="~/Scripts/bubble_tree/Tween.js"></script>
    <script src="~/Scripts/bubble_tree/jquery-migrate.min.js"></script>
    <link href="~/Content/bubble_tree/bubbletree.css" rel="stylesheet" />
    @*<link href="~/Content/bubble_tree/page.css" rel="stylesheet" />*@
    @*<link href="~/Content/bubble_tree/tooltip.css" rel="stylesheet" />*@



    <script type="text/javascript">

        $(function () {
            var data = {
                label: 'Total',
                amount: @{
                int total = 0;
                foreach (var item in Model.schoolCount) { total += item.count; }
                <text>@total,</text>
                }
                color: '#0066bb',  // color for root node, will be inherited by children
                children: [
                    @foreach (var item in Model.schoolCount){<text>{label: '@item.schoolName', amount: @item.count},</text>}
                ]
            };


            var bubbleTree = new BubbleTree({
                data: data,
                container: '.bubbletree'
            });
            bubbleTree.config.bubbleType="donut";


        });

    </script>
}
@* the reason this part is in a section block is that it need to span across to the edge of the page *@
@section bubbleTree{

    <div class="container-fluid bubbletree-wrapper">

        <div class="bubbletree"></div>
        <div class="container body-content">
            <div class="row">
                <div class="col-md-6">

                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#mostRecent">Most Recent</a></li>
                        <li><a data-toggle="tab" href="#mostView">Most Viewed</a></li>
                        <li><a data-toggle="tab" href="#mostDownloaded">Most Cited</a></li>
                        @*<li><a data-toggle="tab" href="#menu3">Menu 3</a></li>*@
                    </ul>

                    <div class="tab-content">
                        <div id="mostRecent" class="tab-pane fade in active">
                            @foreach (var item in Model.mostRecentFeed)
                            {
                                <h4>@Html.ActionLink(@item.title, "Details", "Researches", new { id = item.id }, null)</h4>
                                @*<p>@Html.DisplayFor(m => item.publishedDate)</p>*@
                                @Html.DisplayFor(modelItem => item.publishedDate)
                                var trimedAbstract = item.abstracts;
                                if (trimedAbstract != null)
                                {
                                    trimedAbstract = trimedAbstract.Substring(0, 150) + "...";
                                    <p><text>@trimedAbstract</text></p>
                                }
                                else { Html.DisplayFor(modelItem => item.abstracts); }
                                
                                <br />
                            }

                        </div>
                        <div id="mostView" class="tab-pane fade">
                            @foreach (var item in Model.mostViewedFeed)
                            {
                                <h4>@Html.ActionLink(@item.title, "Details", "Researches", new { id = item.id }, null)</h4>
                                <p>Visits: @item.views</p>
                     
                                var trimedAbstract = item.abstracts;
                                if (trimedAbstract != null)
                                {
                                    trimedAbstract = trimedAbstract.Substring(0, 150) + "...";
                                    <p><text>@trimedAbstract</text></p>
                                }
                                else { Html.DisplayFor(modelItem => item.abstracts); }
                                
                                <br />
                            }
                        </div>
                        <div id="mostDownloaded" class="tab-pane fade">
                            @foreach (var item in Model.mostDownloadedFeed)
                            {
                                <h4>@Html.ActionLink(@item.title, "Details", "Researches", new { id = item.id }, null)</h4>
                                <p>Cited: @item.downloads</p>
                       
                                var trimedAbstract = item.abstracts;
                                if (trimedAbstract != null)
                                {
                                    trimedAbstract = trimedAbstract.Substring(0, 150) + "...";
                                    <p><text>@trimedAbstract</text></p>
                                }
                                else { Html.DisplayFor(modelItem => item.abstracts); }
                                
                                <br />
                            }
                        </div>
                    </div>

                </div>

                <div class="col-md-6">
                    @*list of schools for total grants*@ 
                    @foreach(var item in Model.totalGrants){
                        <p>
                            <h4>@Html.ActionLink(@item.schoolName, "Details", "Schools", new { id = item.id }, null)
                            </h4>
                            Total Grants: $@item.totalGrants
                        </p>
                        
                        
                    }


                </div>
            </div>

        </div>

    </div>
}





@section scripts{


}